package:
  name: vedastro
  version: 1.0.0
source:
  git_rev:0.1
  git_url:https://github.com/VedAstro/VedAstro.Python.git
build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - packaging
    - pythonnet
about:
  home: https://github.com/vedastro/vedastro
  license: MIT
  license_family: MIT
  summary: An open source Python library for advanced astronomical calculations like planet longitude, house sign, shadbala, etc...
  description: An open source Python library for advanced astronomical calculations like planet longitude, house sign, shadbala, etc...
  doc_url: https://github.com/vedastro/vedastro
  dev_url: https://github.com/vedastro/vedastro
extra:
  recipe-maintainers:
    - vedastro
